services:
  conduit:
    image: conduit
    container_name: conduit
    volumes:
      - "db:/data/"
    environment:
      - CONDUIT_SERVER_NAME=matrix.mydomain.com
      - CONDUIT_DATABASE_PATH=/data
      - CONDUIT_DATABASE_BACKEND=rocksdb
      - CONDUIT_PORT=6167
      - CONDUIT_MAX_REQUEST_SIZE=20000000
      - CONDUIT_ALLOW_REGISTRATION=true
      - CONDUIT_ALLOW_FEDERATION=true
      - CONDUIT_TRUSTED_SERVERS=["matrix.org"]
      - CONDUIT_ADDRESS=0.0.0.0
      - CONDUIT_CONFIG=''

volumes:
    db:
