app = "conduit"

[build]
image = "matrixconduit/matrix-conduit:latest"

[env]
CONDUIT_SERVER_NAME             = "matrix.miao.dev"
CONDUIT_DATABASE_BACKEND        = "rocksdb"
CONDUIT_DATABASE_PATH           = "/conduit/"
CONDUIT_ADDRESS                 = "0.0.0.0"
CONDUIT_PORT                    = "6167"
CONDUIT_ALLOW_REGISTRATION      = "true"
CONDUIT_ALLOW_FEDERATION        = "true"
CONDUIT_MAX_REQUEST_SIZE        = "20000000"
CONDUIT_TRUSTED_SERVERS         = ["matrix.org"]
CONDUIT_MAX_CONCURRENT_REQUESTS = "100"
CONDUIT_LOG                     = "info,rocket=off,_=off,sled=off"

[mounts]
source      = "conduit"
destination = "/conduit"

[[services]]
internal_port = 6167
protocol      = "tcp"

[services.concurrency]
hard_limit = 100
soft_limit = 80
type       = "connections"

[[services.ports]]
handlers = ["tls", "http"]
port     = 8448

[[services.ports]]
handlers = ["tls", "http"]
port     = 443
